# Generated by Django 3.2.16 on 2022-11-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'verbose_name': 'Количество ингридиента в рецепте', 'verbose_name_plural': 'Количество ингридиентов в рецепте'},
        ),
    ]
