# Generated by Django 2.2.16 on 2022-10-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=50, verbose_name='Роль'),
        ),
    ]
